# Generated by Django 3.0.7 on 2020-06-17 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlackApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('signing_secret', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('bot_user_oauth_access_token', models.CharField(max_length=57, validators=[django.core.validators.MinLengthValidator(57)])),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=15)),
                ('message_text', models.TextField()),
                ('fallback_text', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='slack_integration.SlackApplication')),
            ],
            options={
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=75)),
                ('actions_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='slack_integration.ActionsBlock')),
            ],
        ),
        migrations.AddField(
            model_name='actionsblock',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.Template'),
        ),
    ]
