# Generated by Django 3.0.7 on 2020-06-10 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback', models.CharField(max_length=100)),
                ('callback_id', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SlackApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('signing_secret', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('bot_user_oauth_access_token', models.CharField(max_length=57, validators=[django.core.validators.MinLengthValidator(57)])),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='slack_integration.SlackApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='slack_integration.Attachment')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.Template'),
        ),
    ]
