# Generated by Django 3.0.8 on 2020-07-10 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('signing_secret', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
                ('bot_user_oauth_access_token', models.CharField(max_length=57, validators=[django.core.validators.MinLengthValidator(57)])),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=15)),
                ('message_text', models.TextField()),
                ('fallback_text', models.CharField(max_length=255)),
                ('thread_subscription', models.BooleanField(default=False)),
                ('callback_url', models.URLField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='slack_integration.SlackApplication')),
            ],
            options={
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActionsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=255, unique=True)),
                ('action_subscription', models.BooleanField(default=False)),
                ('callback_url', models.URLField(blank=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions_block', to='slack_integration.Template')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_timestamps', to='slack_integration.Template')),
            ],
            options={
                'unique_together': {('template', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=75)),
                ('actions_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='slack_integration.ActionsBlock')),
            ],
            options={
                'unique_together': {('actions_block', 'text'), ('actions_block', 'action_id')},
            },
        ),
    ]
