# Generated by Django 3.0.8 on 2020-07-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='channel_name',
            new_name='channel_id',
        ),
    ]
