# Generated by Django 3.0.7 on 2020-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackapplication',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
