# Generated by Django 3.0.7 on 2020-06-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_auto_20200617_0921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='button',
            unique_together={('actions_block', 'action_id', 'text')},
        ),
    ]
