# Generated by Django 3.0.8 on 2020-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_messagetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsblock',
            name='block_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
