# Generated by Django 3.0.7 on 2020-06-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0002_auto_20200610_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('application', 'name')},
        ),
    ]
