# Generated by Django 3.0.8 on 2020-07-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0003_auto_20200709_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionsblock',
            old_name='endpoint',
            new_name='callback_url',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='endpoint',
            new_name='callback_url',
        ),
    ]
