# Generated by Django 3.0.7 on 2020-06-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0003_auto_20200623_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='button',
            unique_together={('actions_block', 'action_id'), ('actions_block', 'text')},
        ),
    ]
